meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  cx: 18
  cy: 18
points:
  zones:
    matrix:
      anchor.shift: [100,-150]
      key: 
        padding: 1ky
        spread: 1kx
      columns:
        pinky: 
          key:
            stagger: 0
            splay: 18
            column_net: c0
        ring:
          key:
            stagger: 16
            splay: -14
            origin: [0,-8.5]
            column_net: c1
        middle:
          key:
            stagger: 6
            splay: -4
            origin: [0,-10]
            column_net: c2
        index:
          key:
            stagger: -10
            splay: -6
            origin: [0,-0]
            column_net: c3
        inner:
          key:
            stagger: -3
            column_net: c4
      rows:
        bottom:
          row_net: r2
        home:
          row_net: r1
        top:
          row_net: r0
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0kx+2, -ky-6]
      key:
        padding: 1ky
        spread: 1kx
        origin: [-kx/2, -ky/2]
      columns:
        layer:
          key:
            splay: 7
            column_net: c3
        space:
          key:
            splay: -12
            column_net: c4
      rows:
        cluster:
          row_net: r3
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
  board:
    - what: rectangle
      where: true
      size: [px,py]
      # connect thumbs
    - what: rectangle
      where: matrix_inner_bottom
      size: [1px,0.6py]
      adjust.shift: [0.0px,-0.5py]
    - what: rectangle
      where: thumbs_layer_cluster
      size: [1px,2py]
      adjust.shift: [0px,0.5py]
    - what: rectangle
      where: thumbs_space_cluster
      size: [1.5px,1py]
      adjust.shift: [-0.25px,0py]
      # close gap between pinky and ring
    - what: rectangle
      where: matrix_pinky_top
      size: [1.5px,1.6py]
      adjust.shift: [0.5px,-0.3py]
      # close gap between ring and middle
    - what: rectangle
      where: matrix_ring_top
      size: [1.5px,2py]
      adjust.shift: [0.5px,-0.5py]
      # close gap between middle and index
    - what: rectangle
      where: matrix_index_top
      size: [1.5px,2py]
      adjust.shift: [-0.5px,-0.5py]
      # space for button over inner column
    - what: rectangle
      where: matrix_index_top
      size: [2kx,1py]
      adjust.shift: [0.5px,0py]
      # close palm gap
    - what: polygon
      operation: add
      points:
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: matrix_index_home
          shift: [0.5px,0.5py]
        - ref: matrix_pinky_home
          shift: [0.5px,0.5py]
    # - what: rectangle
    #   where: [matrix_pinky_bottom]
    #   size: [4px,2py]
    #   adjust.shift: [1.5px,0.5py]
      # mcu spot
    - what: rectangle
      where: thumbs_space_cluster
      size: [1.0px+4,1.0py+2]
      adjust.shift: [0px-2,1py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  pcb:
    template: kicad8
    outlines.main.outline: board
    footprints:
      mcu:
        what: mcu_xiao_ble
        where:
          ref: thumbs_space_cluster
          shift: [0kx-1.5,1ky+3]
          rotate: 0
        params:
          side: "F"
          reversible: true
          enable_nfc: false

          P1: c0

          P3: r0
          P4: r1
          P5: r2
          P6: r3

          P7: c1
          P8: c2
          P9: c3
          P10: c4
      jumper_pad_2:
        what: jumper_pad
        where:
          ref: thumbs_space_cluster
          shift: [0kx-1.5-5.5,1ky+3+5]
          rotate: 0
        params:
          reversible: true
          P_1_1: c0
          P_1_2: c0
          P_2_1: c0
          P_2_2: GND
      jumper_pad_gnd:
        what: jumper_pad
        where:
          ref: thumbs_space_cluster
          shift: [0kx-1.5+5.5,1ky+3+5]
          rotate: 180
        params:
          reversible: true
          P_1_1: GND
          P_1_2: GND
          P_2_1: GND
          P_2_2: c0
      choc_v2_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true 
        adjust:
          rotate: 180 
        params:
          include_keycap: true 
          keycap_width: cx
          keycap_height: cy
          choc_v1_support: false
          choc_v2_support: true 
          reversible: true
          hotswap: true 
          include_stabilizer_pad: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true 
        params:
          reversible: true
          include_traces_vias: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 4.93]
      power_switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_inner_top
          shift: [0kx, 0.5ky+2.4]
          rotate: 90
        params:
          reversible: true 
          from: BAT_P
          to: BAT_P
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: matrix_pinky_top
          shift: [0.5kx+4, 0.5ky-0.6]
        params:
          reversible: true
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_ring_bottom
          shift: [0.0px-4,-0.5px-4]
          rotate: 90
        params: 
          reversible: true
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: matrix_inner_bottom
        params:
          text: JLCJLCJLCJLC
          reversible: true
        adjust:
          shift: [0,-kx/2-1.5]
      info_text_1:
        what: ceoloide/utility_text
        where: matrix_middle_bottom
        params:
          text: "nightjar34"
          width: 4
          height: 4
          bold: true
          italic: true
          reversible: true
        adjust:
          shift: [6,-1py-8]
      info_text_2:
        what: ceoloide/utility_text
        where: matrix_middle_bottom
        params:
          text: "@rejyr"
          width: 2
          height: 2
          bold: true
          italic: true
          reversible: true
        adjust:
          shift: [6+10,-1py-13]
cases:
