meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  cx: 18
  cy: 18
points:
  zones:
    matrix:
      anchor.shift: [100,-150]
      key: 
        padding: 1ky
        spread: 1kx
      columns:
        pinky: 
          key:
            stagger: 0
            splay: 18
            column_net: c0
        ring:
          key:
            stagger: 14
            splay: -18
            origin: [0,-8]
            column_net: c1
        middle:
          key:
            stagger: 6
            column_net: c2
        index:
          key:
            stagger: -10
            column_net: c3
        inner:
          key:
            stagger: -3
            column_net: c4
      rows:
        bottom:
          row_net: r2
        home:
          row_net: r1
        top:
          row_net: r0
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx/3, -ky-2]
      key:
        padding: 1ky
        spread: 1kx
        origin: [-kx/2, -ky/2]
      columns:
        layer:
          key:
            splay: 0
            column_net: c3
        space:
          key:
            splay: -10
            column_net: c4
      rows:
        cluster:
          row_net: r3
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
  board:
    - what: rectangle
      where: true
      size: [px,py]
      # connect thumbs
    - what: rectangle
      where: [matrix_inner_bottom]
      size: [1px,1py]
      adjust.shift: [0.0px,-0.5py]
    - what: rectangle
      where: [thumbs_layer_cluster]
      size: [1.2px,2py]
      adjust.shift: [0.1px,1py]
      # close gap between pinky and ring
    - what: rectangle
      where: [matrix_pinky_top]
      size: [2px,2py]
      adjust.shift: [1px,-0.5py]
      # space for mcu
    - what: rectangle
      where: [matrix_ring_top]
      size: [1px+10.1*2,2py]
      adjust.shift: [-0.5px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  pcb:
    template: kicad8
    outlines.main.outline: board
    footprints:
      mcu:
        what: mcu_xiao_ble
        where:
          ref: matrix_middle_top
          shift: [-2kx-1.5,0ky-6]
          rotate: 90
        params:
          side: "F"
          reversible: true
          P1: r0
          P3: r1
          P4: r2
          P5: r3
          P6: c0
          P7: c1
          P8: c2
          P9: c3
          P10: c4
      choc_v2_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true 
        adjust:
          rotate: 180 
        params:
          include_keycap: true 
          keycap_width: cx
          keycap_height: cy
          choc_v1_support: false
          choc_v2_support: true 
          reversible: true
          hotswap: true 
          include_stabilizer_pad: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true 
        params:
          reversible: true
          include_traces_vias: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 4.93]
      power_switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_inner_top
          shift: [kx, 0ky]
        params:
          reversible: true 
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: matrix_inner_home
          shift: [kx, 0ky]
        params:
          reversible: true 
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_inner_home
          shift: [2kx, 0ky]
        params:
          reversible: true
cases:
